option(ENABLE_CCACHE "Use sccache/ccache to speed up recompilation" ON)

if(NOT ENABLE_CCACHE)
    return()
endif()

set(_SCCACHE_EXE "${CMAKE_SOURCE_DIR}/tools/sccache/sccache-v0.15.0-x86_64-pc-windows-msvc/sccache.exe")
set(_CCACHE_EXE "${CMAKE_SOURCE_DIR}/tools/ccache/ccache-4.13.6-windows-x86_64/ccache.exe")
set(_SCCACHE_WRAPPER "${CMAKE_SOURCE_DIR}/tools/sccache-wrapper.cmd")
set(_CCACHE_WRAPPER "${CMAKE_SOURCE_DIR}/tools/ccache-wrapper.cmd")

if(EXISTS "${_SCCACHE_WRAPPER}")
    set(COMPILER_CACHE_PROGRAM "${_SCCACHE_WRAPPER}")
    set(COMPILER_CACHE_NAME "sccache")
elseif(EXISTS "${_SCCACHE_EXE}")
    set(COMPILER_CACHE_PROGRAM "${_SCCACHE_EXE}")
    set(COMPILER_CACHE_NAME "sccache")
elseif(EXISTS "${_CCACHE_WRAPPER}")
    set(COMPILER_CACHE_PROGRAM "${_CCACHE_WRAPPER}")
    set(COMPILER_CACHE_NAME "ccache")
elseif(EXISTS "${_CCACHE_EXE}")
    set(COMPILER_CACHE_PROGRAM "${_CCACHE_EXE}")
    set(COMPILER_CACHE_NAME "ccache")
else()
    find_program(SCCACHE_PROGRAM NAMES sccache sccache.exe)
    find_program(CCACHE_PROGRAM NAMES ccache ccache.exe)

    if(SCCACHE_PROGRAM)
        set(COMPILER_CACHE_PROGRAM "${SCCACHE_PROGRAM}")
        set(COMPILER_CACHE_NAME "sccache")
    elseif(CCACHE_PROGRAM)
        set(COMPILER_CACHE_PROGRAM "${CCACHE_PROGRAM}")
        set(COMPILER_CACHE_NAME "ccache")
    else()
        message(STATUS "No compiler cache found; run tools/ensure-compiler-cache.ps1 or set ENABLE_CCACHE=OFF")
        return()
    endif()
endif()

set(CMAKE_C_COMPILER_LAUNCHER "${COMPILER_CACHE_PROGRAM}" CACHE STRING "C compiler launcher" FORCE)
set(CMAKE_CXX_COMPILER_LAUNCHER "${COMPILER_CACHE_PROGRAM}" CACHE STRING "C++ compiler launcher" FORCE)

message(STATUS "Using ${COMPILER_CACHE_NAME}: ${COMPILER_CACHE_PROGRAM}")
